### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by tony1509** [csci3250-2019/project-team-f#11]
Make sure you have created an issue before you start work on :)
That is to sure who does what 👍

**Comment by wongtc8** [comment]
Yeah! That's one of the requirements (and I did create an issue for my assigned issue 1 at #3)

**Comment by tony1509** [comment]
Because I saw someone created the project board but no one is there to claim the credit 😢

**Comment by wongtc8** [comment]
> Because I saw someone created the project board but no one is there to claim the credit 😢

Yes, I noticed that as well. And also the same happens to issue-2, @RitoGamingPLZ

**Comment by tony1509** [comment]
Also make sure to introduce yourself in project - introductions!
