### ISSUE TITLE
Task 4

### ISSUE THREAD

**Issue by tony1509** [csci3250-2019/project-team-f#12]
I will be the one who type the c code 😁 
Any suggestions what should I make?

Task specification:

> #4: Write C code
> Please start to remember what you have done for C class. Or learn it anew.
> 
> Your tasks:
> 
> In code.c, write a piece of very simple (yet correct) C code (e.g. Hello World, simple for loop, simple if...then...else, etc.)
> In readme.md, include your code (either copy & paste or include_relative)
> Read this article to see how to get the GitHub shield for Travis CI, and put it inside readme.md with your code: https://hackernoon.com/continuous-integration-using-travis-on-github-1f7f2314b6b7
> (Note: Travis CI is already installed on this repo)

**Comment by tony1509** [comment]
BTW I will also make changes to the 
#code
part in README.md when I am done with the code

**Comment by Henryhin** [comment]
I'm gonna do this task with you,
> 4.If you want to work on that issue, go to the Issues tab and create an issue with the name and contents in issues/taskX.md, then assign yourself to this issue

> 5.After you are done, assign another team member that can help you double check , or you may need to wait when more people join your team

After reading this, do you think whether i need to open one more **issue**?
Or you just need to assign me to this **issue**?

**Comment by Henryhin** [comment]
By the way, besides writing (Hello World, for/while loop, if...then...else),
we can also write something like **array**, **pointers**, **switch**, **simple function**.

**Comment by tony1509** [comment]
I think you can just assign to this issue because it is pretty messy with 16-17 issues. (we have 16-17 people in one team)

And those are great ideas! 👍

**Comment by tony1509** [comment]
Almost done, just wait for issue 2 and 3 to be done 👍

**Comment by tony1509** [comment]
It's proudly done!
