### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by RitoGamingPLZ** [csci3250-2019/project-team-f#13]

**Comment by tony1509** [comment]
Have you read task.md? If not then you really should read it. 

What we want to say is written in task.md: 

> If you want to work on that issue, go to the Issues tab and create an issue with the name and contents in issues/taskX.md, then assign yourself to this issue

Also

> Every student should work on no more than ONE issue

So if you are the one who created the project board, you can leave Task 2 to others, and crerat an issue, assign yourself to it, and close the issue 😄
