### ISSUE TITLE
#2: Include data into readme

### ISSUE THREAD

**Issue by tony1509** [csci3250-2019/project-team-f#21]
Who want to do this one just assign yourself on the right (Assignees)
![here](https://user-images.githubusercontent.com/46753871/56453548-822d4e80-6333-11e9-850d-457b3f580150.png)

> #2: Include data into readme
> You are going to update this website: https://csci3250-2019.github.io/(repo name)
> 
> Please read about include_relative on this page: https://jekyllrb.com/docs/includes/
> 
> Here are your tasks:
> 
> 1. Edit readme.md
> 2. Under Contributors, use include_relative to include your own md file under the folder _stu
> 3. At the bottom of the page, include the last updated time using site.time (HOW?)
> (Feel free to enhance the page outlook by changing the theme, or preparing new CSS!)

**Comment by calvinc0630** [comment]
There are are some newcommers. We need to include their md file into readme.md.

**Comment by calvinc0630** [comment]
#48

**Comment by calvinc0630** [comment]
If there are no newcomers, someone please close this issue.

**Comment by calvinc0630** [comment]
If there are no more newcomers, please close this issues.
