### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by tony1509** [csci3250-2019/project-team-f#22]
Who did this one just assign yourself and close this issue :)

Assign yourself here
![image](https://user-images.githubusercontent.com/46753871/56453564-c91b4400-6333-11e9-94fc-21024b22c9c4.png)

> #3: Project board
> Please explore the Projects tab
> 
> Your tasks:
> 
> 1. Create a new project board (with any name), and use the Basic Kanban template, containing "To do", "In Progress", and "Done"
> 2. Set up these automations:
> - When pull requests are added, put the item in "In progress"
> - When issues are closed, put the item in "Done"
> - When pull requests are merged, put the item in "Done"
> 3. Regularly visit the Issues and Pull requests tabs to make sure all items are marked with your project board

**Comment by tony1509** [comment]
ANYONE????

**Comment by RitoGamingPLZ** [comment]
sorry forget to assign my name

**Comment by tony1509** [comment]
So you did it lol
Next time remember to create an issue, assign your name before doing any changes if working in a big team :P 
Because it may be confusing if some changes suddenly pops out
